export const INCUBATION_TOTAL_DAYS = 21
export const CANDLING_WINDOW_START_DAY = 7
export const CANDLING_TARGET_DAY = 10
export const CANDLING_WINDOW_END_DAY = 14
export const LOCKDOWN_DAY = 18

export const CANDLING_WINDOW_LABEL = `Day ${CANDLING_WINDOW_START_DAY}-${CANDLING_WINDOW_END_DAY}`
export const CANDLING_TARGET_LABEL = `Target Day ${CANDLING_TARGET_DAY}`
export const LOCKDOWN_LABEL = `Day ${LOCKDOWN_DAY}`
